#!/usr/bin/python
from subprocess import Popen
import sys

filename = "serve.py --port=7500"
while True:
    print("\nStarting " + filename)
    p = Popen("python " + filename, shell=True)
    p.wait()
